debug: true
endpoints:
    health:
        sensitive: false
    shutdown:
        enabled: true

info:
    id: ${spring.application.name}
logging:
    level:
        org:
            springframework:
                security: DEBUG
management:
    contextPath: /admin
spring:
    cloud:
        config:
            discovery:
                enabled: true
        consul:
            discovery:
                hostname: localhost
            host: localhost
    jpa:
        generate-ddl: true
    sleuth:
        log:
            json:
                enabled: true
        sampler:
            percentage: 1.0
    zipkin:
        base-url: http://127.0.0.1:9411
        host: localhost
