debug: true
endpoints:
    health:
        sensitive: false
    shutdown:
        enabled: true
eureka:
    client:
        healthcheck:
            enabled: true
    instance:
        hostname: 127.0.0.1
        preferIpAddress: true
    server:
        a-sgcache-expiry-timeout-ms: 60000
        eviction-interval-timer-in-ms: 30000
        peer-eureka-nodes-update-interval-ms: 15000
        registry-sync-retries: 5
        registry-sync-retry-wait-ms: 500
        renewal-threshold-update-interval-ms: 300000
info:
    id: ${spring.application.name}
logging:
    level:
        org:
            springframework:
                security: DEBUG
management:
    contextPath: /admin
spring:
    cloud:
        config:
            discovery:
                enabled: true
        consul:
            discovery:
                hostname: localhost
            host: localhost
    jpa:
        generate-ddl: true
    sleuth:
        log:
            json:
                enabled: true
        sampler:
            percentage: 1.0
    zipkin:
        base-url: http://127.0.0.1:9411
        host: localhost
